# Generated by Django 2.2 on 2019-05-13 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_pizzeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='dateMenu',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
