# Generated by Django 2.2 on 2019-05-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_pizzeria_datemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaSize', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'XXL')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Pizza')),
                ('pizzeria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Pizzeria')),
            ],
        ),
    ]
