# Generated by Django 2.2 on 2019-05-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_positioninmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAndSurname', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=40)),
                ('streetNumber', models.CharField(max_length=5)),
                ('houseNumber', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=30)),
                ('phoneNumber', models.DecimalField(decimal_places=0, max_digits=9)),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Pizzeria')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.OrderData')),
                ('positionInMenu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Pizza')),
            ],
        ),
    ]
