# Generated by Django 2.2 on 2019-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_orderdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='pizzeria',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
