# Generated by Django 2.2 on 2019-05-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20190526_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='pizzeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Pizzeria'),
        ),
    ]
