# Generated by Django 2.2 on 2019-05-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20190526_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='numberOfPIM',
            field=models.IntegerField(default=0),
        ),
    ]
