# Generated by Django 2.2 on 2019-05-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_orderposition_numberofpim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='positionInMenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.PositionInMenu'),
        ),
    ]
