# Generated by Django 2.2 on 2019-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20190526_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='orderNumber',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='orderStatus',
            field=models.CharField(choices=[('1', 'Zamówienie przyjęte'), ('2', 'Zamówienie w trakcie przygotowania'), ('3', 'Zamówienie jest pakowane'), ('4', 'Zamówienie w dowozie')], default='1', max_length=1),
        ),
    ]
