# Generated by Django 2.2 on 2019-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20190527_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='numberOfDrinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='numberOfSauces',
            field=models.IntegerField(default=0),
        ),
    ]
