# Generated by Django 2.2 on 2019-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20190528_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='drink',
            field=models.CharField(choices=[('1', 'Pepsi'), ('2', 'Coca Cola'), ('3', 'Sprite'), ('4', 'Sok pomarańczowy'), ('5', 'Woda')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='sauce',
            field=models.CharField(choices=[('1', 'Sos pomidorowy'), ('2', 'Sos czosnkowy'), ('3', 'Sos BBQ'), ('4', 'Sos orientalny'), ('5', 'Sos tysiąca wysp')], default='', max_length=1),
        ),
    ]
