# Generated by Django 2.2 on 2019-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20190528_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='pay',
            field=models.CharField(choices=[('1', 'Gotówka (przy odbiorze)'), ('2', 'Karta płatnicza'), ('3', 'Przelew')], default='1', max_length=1),
        ),
    ]
