# Generated by Django 2.2 on 2019-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_orderdata_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='numberOfDrinks',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='numberOfSauces',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='sauce',
        ),
        migrations.AddField(
            model_name='pizza',
            name='looseOfPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
