# Generated by Django 2.2 on 2019-05-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20190528_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positioninmenu',
            old_name='pizza_id',
            new_name='Pizza_FK',
        ),
    ]
