# Generated by Django 2.2 on 2019-05-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20190528_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('discount', models.IntegerField(default=5)),
                ('numberOfCoupons', models.IntegerField(default=1)),
            ],
        ),
    ]
