# Generated by Django 2.2 on 2019-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20190528_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='favorite_fruit',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default='orange', max_length=10),
        ),
    ]
