# Generated by Django 2.2 on 2019-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_orderdata_favorite_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='favorite_fruit',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='pay',
            field=models.CharField(choices=[('1', 'Gotówka (przy odbiorze)'), ('2', 'Karta płatnicza'), ('3', 'Przelew')], default='1', max_length=1),
        ),
    ]
