# Generated by Django 2.2 on 2019-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_auto_20190529_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='drink',
            field=models.CharField(choices=[('1', 'Pepsi'), ('2', 'Coca Cola'), ('3', 'Sprite'), ('4', 'Sok pomarańczowy'), ('5', 'Woda')], default='5', max_length=1),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='numberOfDrinks',
            field=models.IntegerField(default=1),
        ),
    ]
