# Generated by Django 2.2 on 2019-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_auto_20190601_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='drink',
            field=models.CharField(choices=[('1', 'Pepsi'), ('2', 'Coca Cola'), ('3', 'Sprite'), ('4', 'Sok pomarańczowy'), ('5', 'Woda'), ('6', 'Bez napoju')], default='5', max_length=1),
        ),
    ]
