# Generated by Django 2.2 on 2019-06-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_auto_20190601_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='numberOfSauces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='sauce',
            field=models.CharField(choices=[('1', 'Sos pomidorowy'), ('2', 'Sos czosnkowy'), ('3', 'Sos BBQ'), ('4', 'Sos orientalny'), ('5', 'Sos tysiąca wysp')], default='1', max_length=1),
        ),
    ]
