# Generated by Django 2.2 on 2019-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_auto_20190602_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='numberOfSauces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='sauce',
            field=models.CharField(choices=[('1', 'Sos pomidorowy'), ('2', 'Sos czosnkowy'), ('3', 'Sos BBQ'), ('4', 'Sos orientalny'), ('5', 'Sos tysiąca wysp'), ('6', 'Bez sosu')], default='6', max_length=1),
        ),
    ]
